CREATE TABLE regions (
id SERIAL,
name VARCHAR(40),
PRIMARY KEY (id)
);

CREATE TABLE users (
id SERIAL,
first_name VARCHAR(40),
last_name VARCHAR(40),
role VARCHAR(10) NOT NULL,
status VARCHAR(10) NOT NULL,
region_id INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE posts (
id SERIAL PRIMARY KEY,
user_id INT NOT NULL,
content TEXT,
created TIMESTAMP NOT NULL DEFAULT now(),
updated TIMESTAMP NOT NULL DEFAULT now(),
status VARCHAR(15) NOT NULL,
CONSTRAINT fk_users FOREIGN KEY (user_id)
REFERENCES users(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);